import { ItineraryItem, TripSettings } from './types';

export const DEFAULT_TRIP_SETTINGS: TripSettings = {
  title: "Road Trip Camping en Thaïlande",
  description: "Un road trip nature exceptionnel à travers les parcs nationaux, les montagnes et les temples sacrés de Thaïlande.",
  startDate: "2026-11-01" // November 1st, 2026 (dry/cool season, perfect for camping!)
};

// Precise coordinates for all default places in Thailand
export const PLACE_COORDINATES: Record<string, { lat: number; lng: number }> = {
  "123/99 Sarintara 1 Village, Samut Sakhon": { lat: 13.5266, lng: 100.3161 },
  "Bangkok": { lat: 13.7563, lng: 100.5018 },
  "Wat Sangkat Rattanakhiri Uthai Thani": { lat: 15.3857, lng: 100.0232 },
  "Mae Wong National Park": { lat: 16.0384, lng: 99.1171 },
  "Si Satchanalai National Park": { lat: 17.5516, lng: 99.4795 },
  "Chae Son National Park": { lat: 18.8354, lng: 99.4716 },
  "Doi Inthanon National Park": { lat: 18.5880, lng: 98.4867 },
  "Chiang Dao": { lat: 19.3667, lng: 98.9667 },
  "Doi Pha Hom Pok National Park": { lat: 20.0416, lng: 99.1418 },
  "Chiang Rai Immigration Office": { lat: 19.9101, lng: 99.8406 },
  "Doi Phu Kha National Park": { lat: 19.2014, lng: 101.0784 },
  "Phu Hin Rong Kla National Park": { lat: 16.9996, lng: 101.1278 },
  "Nam Nao National Park": { lat: 16.7411, lng: 101.5739 },
  "Khao Yai National Park": { lat: 14.4393, lng: 101.3725 }
};

export const DEFAULT_ITINERARY: ItineraryItem[] = [
  {
    id: "item-1",
    placeName: "123/99 Sarintara 1 Village, Samut Sakhon",
    day: 1,
    category: "Lodging",
    notes: "Logement chez l'habitant (Gratuit) - Départ du road trip",
    lat: 13.5266,
    lng: 100.3161,
    duration: "1 nuit",
    budget: 0,
    imageUrl: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=600&q=80",
    detailedTips: "Logement chez l'habitant gratuit. Adresse exacte : 123/99 Sarintara 1 Village, Khok Kham Subdistrict, Mueang Samut Sakhon District, Samut Sakhon 74000. Profitez-en pour vous reposer et planifier le départ. Achetez vos cartouches de gaz à vis (230g ou 450g) chez Decathlon Rama IV à Bangkok avant de prendre la route vers le Nord.",
    maxInfo: "Un accueil chaleureux et gratuit chez l'habitant. Idéal pour commencer le road trip en toute sérénité et s'immerger directement dans la vie locale thaïlandaise."
  },
  {
    id: "item-2",
    placeName: "Wat Sangkat Rattanakhiri Uthai Thani",
    day: 1,
    category: "Attraction",
    notes: "Événement Tak Bat Devo et nuit au bord de la rivière",
    lat: 15.3857,
    lng: 100.0232,
    duration: "4h",
    budget: 200,
    imageUrl: "https://images.unsplash.com/photo-1598977123418-45f04b01d4ae?auto=format&fit=crop&w=600&q=80",
    detailedTips: "Montez les 449 marches menant au temple sacré au sommet du mont Sakaekrang pour admirer le lever du soleil sur la province d'Uthai Thani.",
    maxInfo: "Ce temple est mondialement célèbre pour l'événement spectaculaire du Tak Bat Devo, célébré à la fin de la retraite bouddhiste des pluies (Ok Phansa), où plus de 500 moines descendent le mont pour recevoir les offranges des fidèles."
  },
  {
    id: "item-3",
    placeName: "Mae Wong National Park",
    day: 2,
    category: "Camping",
    notes: "Camping Khun Nam Yen - Chong Yen et cascade Khlong Lan",
    lat: 16.0384,
    lng: 99.1171,
    duration: "3 nuits",
    budget: 300,
    imageUrl: "https://images.unsplash.com/photo-1546182990-dffeafbe841d?auto=format&fit=crop&w=600&q=80",
    detailedTips: "Prévoyez des vêtements très chauds pour la nuit. Chong Yen est réputé pour son vent constant et ses températures fraîches (parfois 12°C). Pensez également à emporter du répulsif contre les petits moucherons de sable de montagne.",
    maxInfo: "L'un des parcs de jungle de montagne les plus sauvages du pays. Le point de vue de Chong Yen est situé à 1 340 mètres d'altitude, offrant des mers de nuages matinales à couper le souffle. Ne manquez pas la cascade de Khlong Lan, un mur d'eau titanesque de 100 mètres de haut."
  },
  {
    id: "item-4",
    placeName: "Si Satchanalai National Park",
    day: 5,
    category: "Camping",
    notes: "Camping rivière - Cascades Tad Dao et ruines jungle",
    lat: 17.5516,
    lng: 99.4795,
    duration: "2 nuits",
    budget: 300,
    imageUrl: "https://images.unsplash.com/photo-1590001155093-a3c66ab0c3ff?auto=format&fit=crop&w=600&q=80",
    detailedTips: "Louez un vélo à l'entrée du parc historique pour environ 30 THB. Cela vous permettra de découvrir l'ensemble des ruines à votre rythme, à l'ombre d'arbres séculaires géants.",
    maxInfo: "Classé au patrimoine mondial de l'UNESCO, ce site abrite les ruines de l'ancienne cité sœur de Sukhothai. Entouré par une jungle luxuriante et des collines préservées, il est incroyablement paisible, authentique, et beaucoup moins fréquenté par les touristes."
  },
  {
    id: "item-5",
    placeName: "Chae Son National Park",
    day: 7,
    category: "Camping",
    notes: "Camping ombragé - Bains chauds naturels et cascades",
    lat: 18.8354,
    lng: 99.4716,
    duration: "3 nuits",
    budget: 300,
    imageUrl: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=600&q=80",
    detailedTips: "Achetez un petit panier d'œufs de caille ou de poule vendus à l'entrée par les locaux et plongez-le dans les sources bouillonnantes à 82°C pour déguster des œufs mollets parfaits cuits par la Terre !",
    maxInfo: "Un joyau caché qui combine des sources chaudes minérales et d'eau douce fraîche. Vous pouvez louer de superbes cabines de bains thermaux privés pour seulement 50 THB. Le camping est ombragé, plat et situé au bord d'une agréable rivière de montagne."
  },
  {
    id: "item-6",
    placeName: "Doi Inthanon National Park",
    day: 10,
    category: "Camping",
    notes: "Camping Dong Son - Sentier Ang Ka et cascade Mae Ya",
    lat: 18.5880,
    lng: 98.4867,
    duration: "3 nuits",
    budget: 300,
    imageUrl: "https://images.unsplash.com/photo-1510070112810-d4e9a46d9e91?auto=format&fit=crop&w=600&q=80",
    detailedTips: "Les nuits au camping de Dong Son (1 300m) peuvent descendre sous les 5°C de novembre à janvier. Louez ou apportez un bon sac de couchage thermique et une veste de montagne.",
    maxInfo: "Le toit de la Thaïlande, culminant à 2 565 mètres. Explorez le sentier de brume moussue Ang Ka, visitez les majestueuses pagodes royales jumelles, et admirez la cascade Mae Ya, l'une des plus spectaculaires d'Asie du Sud-Est avec ses chutes en gradins."
  },
  {
    id: "item-7",
    placeName: "Chiang Dao",
    day: 13,
    category: "Camping",
    notes: "Vue falaises calcaires - Grottes et sources Pong Ar-nong",
    lat: 19.3667,
    lng: 98.9667,
    duration: "3 nuits",
    budget: 450,
    imageUrl: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=600&q=80",
    detailedTips: "Pour visiter les grottes non éclairées de Chiang Dao, engagez obligatoirement l'un des guides locaux équipés d'une lanterne à gaz de camping traditionnelle à l'entrée (environ 150 THB).",
    maxInfo: "Dominé par le Doi Luang Chiang Dao, le troisième plus haut sommet calcaire du pays (2 175 mètres). Le village propose de magnifiques sources chaudes publiques en plein air nichées dans une nature verdoyante."
  },
  {
    id: "item-8",
    placeName: "Doi Pha Hom Pok National Park",
    day: 16,
    category: "Camping",
    notes: "Camping altitude - Geysers et sources de Fang",
    lat: 20.0416,
    lng: 99.1418,
    duration: "3 nuits",
    budget: 300,
    imageUrl: "https://images.unsplash.com/photo-1547036967-23d11aacaee0?auto=format&fit=crop&w=600&q=80",
    detailedTips: "Commandez un brûleur Mookata traditionnel (barbecue/fondue thaïlandaise) à l'accueil du parc pour votre dîner sous les étoiles au camping d'altitude de Kiew Lom.",
    maxInfo: "Le deuxième plus haut sommet de Thaïlande (2 285m). Connu pour ses geysers d'eau thermale jaillissants à plus de 50 mètres de haut et ses sentiers escarpés offrant un superbe lever de soleil sur la mer de nuages."
  },
  {
    id: "item-9",
    placeName: "Chiang Rai Immigration Office",
    day: 19,
    category: "Lodging",
    notes: "HÔTEL : Formalités Extension Visa 24h + Lessives",
    lat: 19.9101,
    lng: 99.8406,
    duration: "2 nuits",
    budget: 1500,
    imageUrl: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=600&q=80",
    detailedTips: "Arrivez au bureau d'immigration dès 8h15 pour faire partie des premiers numéros d'attente. Apportez votre formulaire TM30 imprimé de votre hôtel pour obtenir votre extension de visa de 30 jours sans accroc.",
    maxInfo: "Une halte stratégique indispensable à la fin de vos 3 premiers de séjour. Profitez d'un hôtel douillet avec piscine à Chiang Rai, faites vos lessives dans les laveries automatiques de la ville, et visitez les célèbres temples Blanc, Noir et Bleu."
  },
  {
    id: "item-10",
    placeName: "Doi Phu Kha National Park",
    day: 21,
    category: "Camping",
    notes: "Camping sommet - Route panoramique 1081 et mer de nuages",
    lat: 19.2014,
    lng: 101.0784,
    duration: "3 nuits",
    budget: 300,
    imageUrl: "https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?auto=format&fit=crop&w=600&q=80",
    detailedTips: "La route 1081 (route du sel historique de Bo Kluea) est sinueuse et très inclinée par endroits. Assurez-vous d'avoir de bons freins et utilisez impérativement le frein moteur en descente.",
    maxInfo: "Situé dans la province reculée de Nan, ce parc abrite la rare plante Chomphu Phu Kha aux fleurs roses et de superbes campings perchés au-dessus de brumes denses."
  },
  {
    id: "item-11",
    placeName: "Phu Hin Rong Kla National Park",
    day: 24,
    category: "Camping",
    notes: "Camping plateau - Rochers Lan Hin Taek et brumes",
    lat: 16.9996,
    lng: 101.1278,
    duration: "3 nuits",
    budget: 300,
    imageUrl: "https://images.unsplash.com/photo-1501854140801-50d01698950b?auto=format&fit=crop&w=600&q=80",
    detailedTips: "Portez de bonnes chaussures de marche adhérentes. Le climat y est humide et les formations rocheuses plates peuvent être glissantes au milieu de la brume.",
    maxInfo: "Situé à 1 200 mètres d'altitude, ce site historique servait de bastion stratégique imprenable pour les insurgés dans les années 1970. On y observe la faille rocheuse géologique de Lan Hin Taek et des mémoriaux d'époque."
  },
  {
    id: "item-12",
    placeName: "Nam Nao National Park",
    day: 27,
    category: "Camping",
    notes: "Camping jungle sauvage - Éléphants et ciel étoilé",
    lat: 16.7411,
    lng: 101.5739,
    duration: "3 nuits",
    budget: 300,
    imageUrl: "https://images.unsplash.com/photo-1473448912268-2022ce9509d8?auto=format&fit=crop&w=600&q=80",
    detailedTips: "Éteignez toutes vos lampes extérieures de camping après 22h pour profiter d'un ciel étoilé d'une pureté rare en Asie. Ne laissez aucun déchet plastique à l'extérieur de la voiture.",
    maxInfo: "Un immense plateau de forêts de pins primordiales relié à des parcs nationaux adjacents. C'est l'un des rares endroits de Thaïlande où vous entendrez et pourrez voir passer de véritables hardes d'éléphants sauvages au coucher du soleil."
  },
  {
    id: "item-13",
    placeName: "Khao Yai National Park",
    day: 30,
    category: "Camping",
    notes: "Camping Lam Ta Khong - Animaux et cascades",
    lat: 14.4393,
    lng: 101.3725,
    duration: "2 nuits",
    budget: 300,
    imageUrl: "https://images.unsplash.com/photo-1581888227599-779811939961?auto=format&fit=crop&w=600&q=80",
    detailedTips: "Ne stockez aucune nourriture odorante ou ouverte dans votre tente. Les cerfs sauvages très curieux et les macaques agiles n'hésiteront pas à éventrer la toile de votre tente pour chiper de la nourriture !",
    maxInfo: "Fondé en 1962, c'est le tout premier parc national de Thaïlande, classé à l'UNESCO. Une faune d'une richesse inégalée y réside : éléphants, gibbons, calaos bicornes géants et loutres de rivière."
  },
  {
    id: "item-14",
    placeName: "Bangkok",
    day: 32,
    category: "Lodging",
    notes: "Fin du road trip et retour",
    lat: 13.7563,
    lng: 100.5018,
    duration: "1 nuit",
    budget: 1000,
    imageUrl: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=600&q=80",
    detailedTips: "Restituez votre véhicule de location l'esprit tranquille. Si vous possédez du matériel de camping acheté en début de séjour, faites-en don à d'autres voyageurs en route ou laissez-les à un hôtel solidaire.",
    maxInfo: "Félicitations ! Vous venez de parcourir les plus beaux parcs naturels de Thaïlande en autonomie. Clôturez votre road-trip inoubliable par un fantastique massage traditionnel de fin de parcours."
  }
];
