import { ItineraryItem, TripSettings } from './types';

export const DEFAULT_TRIP_SETTINGS: TripSettings = {
  title: "Road Trip Camping en Thaïlande",
  description: "Un road trip nature exceptionnel à travers les parcs nationaux, les montagnes et les temples sacrés de Thaïlande.",
  startDate: "2026-11-01" // November 1st, 2026 (dry/cool season, perfect for camping!)
};

// Precise coordinates for all default places in Thailand
export const PLACE_COORDINATES: Record<string, { lat: number; lng: number }> = {
  "123/99 Sarintara 1 Village, Samut Sakhon": { lat: 13.5266, lng: 100.3161 },
  "Bangkok": { lat: 13.7563, lng: 100.5018 },
  "Wat Sangkat Rattanakhiri Uthai Thani": { lat: 15.3857, lng: 100.0232 },
  "Mae Wong National Park": { lat: 16.0384, lng: 99.1171 },
  "Si Satchanalai National Park": { lat: 17.5516, lng: 99.4795 },
  "Chae Son National Park": { lat: 18.8354, lng: 99.4716 },
  "Doi Inthanon National Park": { lat: 18.5880, lng: 98.4867 },
  "Chiang Dao": { lat: 19.3667, lng: 98.9667 },
  "Doi Pha Hom Pok National Park": { lat: 20.0416, lng: 99.1418 },
  "Chiang Rai Immigration Office": { lat: 19.9101, lng: 99.8406 },
  "Doi Phu Kha National Park": { lat: 19.2014, lng: 101.0784 },
  "Phu Hin Rong Kla National Park": { lat: 16.9996, lng: 101.1278 },
  "Nam Nao National Park": { lat: 16.7411, lng: 101.5739 },
  "Khao Yai National Park": { lat: 14.4393, lng: 101.3725 }
};

export const DEFAULT_ITINERARY: ItineraryItem[] = [
  {
    id: "item-1",
    placeName: "123/99 Sarintara 1 Village, Samut Sakhon",
    day: 1,
    category: "Lodging",
    notes: "Logement chez l'habitant (Gratuit) - Départ du road trip",
    lat: 13.5266,
    lng: 100.3161,
    duration: "1 nuit",
    budget: 0,
    imageUrl: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=600&q=80",
    detailedTips: "Logement chez l'habitant gratuit. Adresse exacte : 123/99 Sarintara 1 Village, Khok Kham Subdistrict, Mueang Samut Sakhon District, Samut Sakhon 74000. Profitez-en pour vous reposer et planifier le départ. Achetez vos cartouches de gaz à vis (230g ou 450g) chez Decathlon Rama IV à Bangkok avant de prendre la route vers le Nord.",
    maxInfo: "Un accueil chaleureux et gratuit chez l'habitant. Idéal pour commencer le road trip en toute sérénité et s'immerger directement dans la vie locale thaïlandaise."
  },
  {
    id: "item-2",
    placeName: "Wat Sangkat Rattanakhiri Uthai Thani",
    day: 1,
    category: "Attraction",
    notes: "Événement Tak Bat Devo et nuit au bord de la rivière",
    lat: 15.3857,
    lng: 100.0232,
    duration: "4h",
    budget: 200,
    imageUrl: "https://images.unsplash.com/photo-1598977123418-45f04b01d4ae?auto=format&fit=crop&w=600&q=80",
    detailedTips: "Montez les 449 marches menant au temple sacré au sommet du mont Sakaekrang pour admirer le lever du soleil sur la province d'Uthai Thani.",
    maxInfo: "Ce temple est mondialement célèbre pour l'événement spectaculaire du Tak Bat Devo, célébré à la fin de la retraite bouddhiste des pluies (Ok Phansa), où plus de 500 moines descendent le mont pour recevoir les offranges des fidèles."
  },
  {
    id: "item-3",
    placeName: "Mae Wong National Park",
    day: 2,
    category: "Camping",
    notes: "Camping Khun Nam Yen - Chong Yen et cascade Khlong Lan",
    lat: 16.0384,
    lng: 99.1171,
    duration: "3 nuits",
    budget: 300,
    imageUrl: "https://images.unsplash.com/photo-1546182990-dffeafbe841d?auto=format&fit=crop&w=600&q=80",
    detailedTips: "Prévoyez des vêtements très chauds pour la nuit. Chong Yen est réputé pour son vent constant et ses températures fraîches (parfois 12°C). Pensez également à emporter du répulsif contre les petits moucherons de sable de montagne.",
    maxInfo: "L'un des parcs de jungle de montagne les plus sauvages du pays. Le point de vue de Chong Yen est situé à 1 340 mètres d'altitude, offrant des mers de nuages matinales à couper le souffle. Ne manquez pas la cascade de Khlong Lan, un mur d'eau titanesque de 100 mètres de haut."
  },
  {
    id: "item-4",
    placeName: "Si Satchanalai National Park",
    day: 5,
    category: "Camping",
    notes: "Camping rivière - Cascades Tad Dao et ruines jungle",
    lat: 17.5516,
    lng: 99.4795,
    duration: "2 nuits",
    budget: 300,
    imageUrl: "https://images.unsplash.com/photo-1590001155093-a3c66ab0c3ff?auto=format&fit=crop&w=600&q=80",
    detailedTips: "Louez un vélo à l'entrée du parc historique pour environ 30 THB. Cela vous permettra de découvrir l'ensemble des ruines à votre rythme, à l'ombre d'arbres séculaires géants.",
    maxInfo: "Classé au patrimoine mondial de l'UNESCO, ce site abrite les ruines de l'ancienne cité sœur de Sukhothai. Entouré par une jungle luxuriante et des collines préservées, il est incroyablement paisible, authentique, et beaucoup moins fréquenté par les touristes."
  },
  {
    id: "item-5",
    placeName: "Chae Son National Park",
    day: 7,
    category: "Camping",
    notes: "Camping ombragé - Bains chauds naturels et cascades",
    lat: 18.8354,
    lng: 99.4716,
    duration: "3 nuits",
    budget: 300,
    imageUrl: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=600&q=80",
    detailedTips: "Achetez un petit panier d'œufs de caille ou de poule vendus à l'entrée par les locaux et plongez-le dans les sources bouillonnantes à 82°C pour déguster des œufs mollets parfaits cuits par la Terre !",
    maxInfo: "Un joyau caché qui combine des sources chaudes minérales et d'eau douce fraîche. Vous pouvez louer de superbes cabines de bains thermaux privés pour seulement 50 THB. Le camping est ombragé, plat et situé au bord d'une agréable rivière de montagne."
  },
  {
    id: "item-6",
    placeName: "Doi Inthanon National Park",
    day: 10,
    category: "Camping",
    notes: "Camping Dong Son - Sentier Ang Ka et cascade Mae Ya",
    lat: 18.5880,
    lng: 98.4867,
    duration: "3 nuits",
    budget: 300,
    imageUrl: "https://images.unsplash.com/photo-1510070112810-d4e9a46d9e91?auto=format&fit=crop&w=600&q=80",
    detailedTips: "Les nuits au camping de Dong Son (1 300m) peuvent descendre sous les 5°C de novembre à janvier. Louez ou apportez un bon sac de couchage thermique et une veste de montagne.",
    maxInfo: "Le toit de la Thaïlande, culminant à 2 565 mètres. Explorez le sentier de brume moussue Ang Ka, visitez les majestueuses pagodes royales jumelles, et admirez la cascade Mae Ya, l'une des plus spectaculaires d'Asie du Sud-Est avec ses chutes en gradins."
  },
  {
    id: "item-7",
    placeName: "Chiang Dao",
    day: 13,
    category: "Camping",
    notes: "Vue falaises calcaires - Grottes et sources Pong Ar-nong",
    lat: 19.3667,
    lng: 98.9667,
    duration: "3 nuits",
    budget: 450,
    imageUrl: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=600&q=80",
    detailedTips: "Pour visiter les grottes non éclairées de Chiang Dao, engagez obligatoirement l'un des guides locaux équipés d'une lanterne à gaz de camping traditionnelle à l'entrée (environ 150 THB).",
    maxInfo: "Dominé par le Doi Luang Chiang Dao, le troisième plus haut sommet calcaire du pays (2 175 mètres). Le village propose de magnifiques sources chaudes publiques en plein air nichées dans une nature verdoyante."
  },
  {
    id: "item-8",
    placeName: "Doi Pha Hom Pok National Park",
    day: 16,
    category: "Camping",
    notes: "Camping altitude - Geysers et sources de Fang",
    lat: 20.0416,
    lng: 99.1418,
    duration: "3 nuits",
    budget: 300,
    imageUrl: "https://images.unsplash.com/photo-1547036967-23d11aacaee0?auto=format&fit=crop&w=600&q=80",
    detailedTips: "Commandez un brûleur Mookata traditionnel (barbecue/fondue thaïlandaise) à l'accueil du parc pour votre dîner sous les étoiles au camping d'altitude de Kiew Lom.",
    maxInfo: "Le deuxième plus haut sommet de Thaïlande (2 285m). Connu pour ses geysers d'eau thermale jaillissants à plus de 50 mètres de haut et ses sentiers escarpés offrant un superbe lever de soleil sur la mer de nuages."
  },
  {
    id: "item-9",
    placeName: "Chiang Rai Immigration Office",
    day: 19,
    category: "Lodging",
    notes: "HÔTEL : Formalités Extension Visa 24h + Lessives",
    lat: 19.9101,
    lng: 99.8406,
    duration: "2 nuits",
    budget: 1500,
    imageUrl: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=600&q=80",
    detailedTips: "Arrivez au bureau d'immigration dès 8h15 pour faire partie des premiers numéros d'attente. Apportez votre formulaire TM30 imprimé de votre hôtel pour obtenir votre extension de visa de 30 jours sans accroc.",
    maxInfo: "Une halte stratégique indispensable à la fin de vos 3 premiers de séjour. Profitez d'un hôtel douillet avec piscine à Chiang Rai, faites vos lessives dans les laveries automatiques de la ville, et visitez les célèbres temples Blanc, Noir et Bleu."
  },
  {
    id: "item-10",
    placeName: "Doi Phu Kha National Park",
    day: 21,
    category: "Camping",
    notes: "Camping sommet - Route panoramique 1081 et mer de nuages",
    lat: 19.2014,
    lng: 101.0784,
    duration: "3 nuits",
    budget: 300,
    imageUrl: "https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?auto=format&fit=crop&w=600&q=80",
    detailedTips: "La route 1081 (route du sel historique de Bo Kluea) est sinueuse et très inclinée par endroits. Assurez-vous d'avoir de bons freins et utilisez impérativement le frein moteur en descente.",
    maxInfo: "Situé dans la province reculée de Nan, ce parc abrite la rare plante Chomphu Phu Kha aux fleurs roses et de superbes campings perchés au-dessus de brumes denses."
  },
  {
    id: "item-11",
    placeName: "Phu Hin Rong Kla National Park",
    day: 24,
    category: "Camping",
    notes: "Camping plateau - Rochers Lan Hin Taek et brumes",
    lat: 16.9996,
    lng: 101.1278,
    duration: "3 nuits",
    budget: 300,
    imageUrl: "https://images.unsplash.com/photo-1501854140801-50d01698950b?auto=format&fit=crop&w=600&q=80",
    detailedTips: "Portez de bonnes chaussures de marche adhérentes. Le climat y est humide et les formations rocheuses plates peuvent être glissantes au milieu de la brume.",
    maxInfo: "Situé à 1 200 mètres d'altitude, ce site historique servait de bastion stratégique imprenable pour les insurgés dans les années 1970. On y observe la faille rocheuse géologique de Lan Hin Taek et des mémoriaux d'époque."
  },
  {
    id: "item-12",
    placeName: "Nam Nao National Park",
    day: 27,
    category: "Camping",
    notes: "Camping jungle sauvage - Éléphants et ciel étoilé",
    lat: 16.7411,
    lng: 101.5739,
    duration: "3 nuits",
    budget: 300,
    imageUrl: "https://images.unsplash.com/photo-1473448912268-2022ce9509d8?auto=format&fit=crop&w=600&q=80",
    detailedTips: "Éteignez toutes vos lampes extérieures de camping après 22h pour profiter d'un ciel étoilé d'une pureté rare en Asie. Ne laissez aucun déchet plastique à l'extérieur de la voiture.",
    maxInfo: "Un immense plateau de forêts de pins primordiales relié à des parcs nationaux adjacents. C'est l'un des rares endroits de Thaïlande où vous entendrez et pourrez voir passer de véritables hardes d'éléphants sauvages au coucher du soleil."
  },
  {
    id: "item-13",
    placeName: "Khao Yai National Park",
    day: 30,
    category: "Camping",
    notes: "Camping Lam Ta Khong - Animaux et cascades",
    lat: 14.4393,
    lng: 101.3725,
    duration: "2 nuits",
    budget: 300,
    imageUrl: "https://images.unsplash.com/photo-1581888227599-779811939961?auto=format&fit=crop&w=600&q=80",
    detailedTips: "Ne stockez aucune nourriture odorante ou ouverte dans votre tente. Les cerfs sauvages très curieux et les macaques agiles n'hésiteront pas à éventrer la toile de votre tente pour chiper de la nourriture !",
    maxInfo: "Fondé en 1962, c'est le tout premier parc national de Thaïlande, classé à l'UNESCO. Une faune d'une richesse inégalée y réside : éléphants, gibbons, calaos bicornes géants et loutres de rivière."
  },
  {
    id: "item-14",
    placeName: "Bangkok",
    day: 32,
    category: "Lodging",
    notes: "Fin du road trip et retour",
    lat: 13.7563,
    lng: 100.5018,
    duration: "1 nuit",
    budget: 1000,
    imageUrl: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=600&q=80",
    detailedTips: "Restituez votre véhicule de location l'esprit tranquille. Si vous possédez du matériel de camping acheté en début de séjour, faites-en don à d'autres voyageurs en route ou laissez-les à un hôtel solidaire.",
    maxInfo: "Félicitations ! Vous venez de parcourir les plus beaux parcs naturels de Thaïlande en autonomie. Clôturez votre road-trip inoubliable par un fantastique massage traditionnel de fin de parcours."
  }
];

export const PRESET_ITINERARIES: { id: string; nameFr: string; nameTh: string; items: ItineraryItem[] }[] = [
  {
    id: "preset-1",
    nameFr: "⛰️ Le Grand Nord sauvage (Parcs & Sommets)",
    nameTh: "⛰️ เส้นทางลุยดอยภาคเหนือและอ่างเก็บน้ำ",
    items: [
      {
        id: "p1-1",
        placeName: "123/99 Sarintara 1 Village, Samut Sakhon",
        day: 1,
        category: "Lodging",
        notes: "Logement chez l'habitant (Gratuit) - Départ du road trip",
        lat: 13.5266,
        lng: 100.3161,
        duration: "1 nuit",
        budget: 0,
        imageUrl: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=600&q=80",
        detailedTips: "Logement chez l'habitant gratuit à Samut Sakhon. Profitez de ce départ serein pour recharger vos batteries et remplir vos réserves d'eau avant de prendre la route vers le nord sauvage.",
        maxInfo: "Un accueil chaleureux chez l'habitant pour débuter votre périple de 4 semaines en toute sérénité."
      },
      {
        id: "p1-2",
        placeName: "Mae Wong National Park",
        day: 5,
        category: "Camping",
        notes: "Camping Khun Nam Yen - Chong Yen et fraîcheur sauvage",
        lat: 16.0384,
        lng: 99.1171,
        duration: "4 nuits",
        budget: 300,
        imageUrl: "https://images.unsplash.com/photo-1546182990-dffeafbe841d?auto=format&fit=crop&w=600&q=80",
        detailedTips: "Prévoyez des pulls épais. Chong Yen (1340m) est connu pour son vent constant et froid la nuit. Utilisez du répulsif puissant contre les petits insectes de sable.",
        maxInfo: "Le point de vue offre des levers de soleil extraordinaires sur les mers de brume tropicales."
      },
      {
        id: "p1-3",
        placeName: "Doi Inthanon National Park",
        day: 11,
        category: "Camping",
        notes: "Camping du sommet de la Thaïlande (Doi Sureya)",
        lat: 18.5880,
        lng: 98.4867,
        duration: "6 nuits",
        budget: 450,
        imageUrl: "https://images.unsplash.com/photo-1510070112810-d4e9a46d9e91?auto=format&fit=crop&w=600&q=80",
        detailedTips: "Louez des duvets épais supplémentaires à l'accueil du parc. Les nuits peuvent descendre sous les 5°C. Visitez la cascade Mae Ya et les pagodes royales au lever du jour.",
        maxInfo: "L'ascension du point culminant de la Thaïlande à 2565 mètres d'altitude, au milieu d'une jungle de brume moussue."
      },
      {
        id: "p1-4",
        placeName: "Doi Pha Hom Pok National Park",
        day: 17,
        category: "Camping",
        notes: "Sources chaudes de Fang et camping d'altitude de Kiew Lom",
        lat: 20.0416,
        lng: 99.1418,
        duration: "6 nuits",
        budget: 450,
        imageUrl: "https://images.unsplash.com/photo-1547036967-23d11aacaee0?auto=format&fit=crop&w=600&q=80",
        detailedTips: "Dégustez un barbecue Mookata traditionnel proposé au camping Kiew Lom sous les étoiles. Prévoyez des vêtements chauds.",
        maxInfo: "Admirez le deuxième plus haut sommet de Thaïlande avec ses geysers d'eaux thermales bouillonnantes."
      },
      {
        id: "p1-5",
        placeName: "Chiang Rai Immigration Office",
        day: 23,
        category: "Lodging",
        notes: "Halte confort à Chiang Rai (Visite du Temple Blanc)",
        lat: 19.9101,
        lng: 99.8406,
        duration: "5 nuits",
        budget: 2500,
        imageUrl: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=600&q=80",
        detailedTips: "Profitez-en pour faire vos lessives en ville et visitez le majestueux temple blanc (Wat Rong Khun) et le temple bleu.",
        maxInfo: "Une pause stratégique idéale après deux semaines intenses de bivouac en altitude."
      },
      {
        id: "p1-6",
        placeName: "Bangkok",
        day: 28,
        category: "Lodging",
        notes: "Retour à Bangkok, restitution et massage final",
        lat: 13.7563,
        lng: 100.5018,
        duration: "1 nuit",
        budget: 1200,
        imageUrl: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=600&q=80",
        detailedTips: "Restituez votre véhicule de location. Terminez ce magnifique périple par un incroyable massage traditionnel thaïlandais.",
        maxInfo: "Clôture d'une aventure inoubliable de 4 semaines au cœur des montagnes sacrées."
      }
    ]
  },
  {
    id: "preset-2",
    nameFr: "🐘 L'Isan sauvage & Plateaux de l'Est (Faune & Temples)",
    nameTh: "🐘 เส้นทางอุทยานแห่งชาติภาคอีสานและประวัติศาสตร์",
    items: [
      {
        id: "p2-1",
        placeName: "123/99 Sarintara 1 Village, Samut Sakhon",
        day: 1,
        category: "Lodging",
        notes: "Départ - Logement chez l'habitant gratuit",
        lat: 13.5266,
        lng: 100.3161,
        duration: "1 nuit",
        budget: 0,
        imageUrl: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=600&q=80",
        detailedTips: "Vérifiez vos provisions et votre réchaud avant le grand départ vers l'Est verdoyant.",
        maxInfo: "Le point de départ parfait pour entamer un road trip mémorable à travers les hauts plateaux."
      },
      {
        id: "p2-2",
        placeName: "Khao Yai National Park",
        day: 5,
        category: "Camping",
        notes: "Camping Lam Ta Khong - Observation des éléphants sauvages",
        lat: 14.4393,
        lng: 101.3725,
        duration: "7 nuits",
        budget: 700,
        imageUrl: "https://images.unsplash.com/photo-1581888227599-779811939961?auto=format&fit=crop&w=600&q=80",
        detailedTips: "Ne laissez absolument aucune nourriture dans votre tente sous peine de la voir déchiquetée par les cerfs ou les macaques curieux.",
        maxInfo: "Classé à l'UNESCO, Khao Yai regorge de cascades majestueuses et d'une faune préservée unique en Asie."
      },
      {
        id: "p2-3",
        placeName: "Wat Sangkat Rattanakhiri Uthai Thani",
        day: 12,
        category: "Attraction",
        notes: "Halte culturelle et visite de la cité historique de Phimai",
        lat: 15.3857,
        lng: 100.0232,
        duration: "6h",
        budget: 500,
        imageUrl: "https://images.unsplash.com/photo-1598977123418-45f04b01d4ae?auto=format&fit=crop&w=600&q=80",
        detailedTips: "Visitez les spectaculaires ruines khmères de Phimai, considérées comme la sœur siamoise d'Angkor Wat au Cambodge.",
        maxInfo: "Un témoignage saisissant de l'époque glorieuse de l'empire d'Angkor au cœur de l'Isan."
      },
      {
        id: "p2-4",
        placeName: "Nam Nao National Park",
        day: 18,
        category: "Camping",
        notes: "Camping de jungle sauvage sous un ciel étoilé pur",
        lat: 16.7411,
        lng: 101.5739,
        duration: "6 nuits",
        budget: 400,
        imageUrl: "https://images.unsplash.com/photo-1473448912268-2022ce9509d8?auto=format&fit=crop&w=600&q=80",
        detailedTips: "Coupez vos projecteurs le soir. Le ciel de Nam Nao est exempt de toute pollution lumineuse, idéal pour l'observation stellaire.",
        maxInfo: "Un immense plateau forestier sauvage reliant de grands écosystèmes montagneux abritant des troupeaux d'éléphants."
      },
      {
        id: "p2-5",
        placeName: "Phu Hin Rong Kla National Park",
        day: 24,
        category: "Camping",
        notes: "Camping sur les formations rocheuses sacrées",
        lat: 16.9996,
        lng: 101.1278,
        duration: "4 nuits",
        budget: 350,
        imageUrl: "https://images.unsplash.com/photo-1501854140801-50d01698950b?auto=format&fit=crop&w=600&q=80",
        detailedTips: "Portez des chaussures adhérentes pour vous promener sur les plaques rocheuses uniques de Lan Hin Taek souvent embrumées.",
        maxInfo: "Bastion historique de maquisards dans les années 70, combinant paysages lunaires et forêts de pins majestueuses."
      },
      {
        id: "p2-6",
        placeName: "Bangkok",
        day: 28,
        category: "Lodging",
        notes: "Fin de l'itinéraire Isan, retour vers la capitale",
        lat: 13.7563,
        lng: 100.5018,
        duration: "1 nuit",
        budget: 1000,
        imageUrl: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=600&q=80",
        detailedTips: "Profitez-en pour restituer le matériel loué et savourer les incroyables stands de Street Food de Bangkok.",
        maxInfo: "Retour en plaine après un périple mémorable à travers les recoins les plus authentiques de l'Est."
      }
    ]
  },
  {
    id: "preset-3",
    nameFr: "🏖️ Le Sud côtier & Îles karstiques (Mer, Lac & Jungle)",
    nameTh: "🏖️ เส้นทางชายทะเลภาคใต้และป่าดิบชื้นเขาสก",
    items: [
      {
        id: "p3-1",
        placeName: "123/99 Sarintara 1 Village, Samut Sakhon",
        day: 1,
        category: "Lodging",
        notes: "Logement chez l'habitant gratuit - Départ vers le grand Sud",
        lat: 13.5266,
        lng: 100.3161,
        duration: "1 nuit",
        budget: 0,
        imageUrl: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=600&q=80",
        detailedTips: "Le point de départ idéal près du littoral pour attaquer la descente de la péninsule thaïlandaise.",
        maxInfo: "Une nuit paisible pour vérifier vos équipements et démarrer vers la mer."
      },
      {
        id: "p3-2",
        placeName: "Si Satchanalai National Park",
        day: 5,
        category: "Camping",
        notes: "Bivouac côtier au parc National de Kaeng Krachan",
        lat: 12.8806,
        lng: 99.5161,
        duration: "6 nuits",
        budget: 600,
        imageUrl: "https://images.unsplash.com/photo-1590001155093-a3c66ab0c3ff?auto=format&fit=crop&w=600&q=80",
        detailedTips: "Grimpez à l'aube vers le point de vue de Phanoen Thung pour admirer une mer de brume spectaculaire se déverser sur le Myanmar voisin.",
        maxInfo: "La plus grande forêt tropicale de Thaïlande, classée au patrimoine mondial de l'UNESCO."
      },
      {
        id: "p3-3",
        placeName: "Wat Sangkat Rattanakhiri Uthai Thani",
        day: 11,
        category: "Attraction",
        notes: "Exploration du parc marin de Khao Sam Roi Yot",
        lat: 12.1667,
        lng: 99.9833,
        duration: "1 jour",
        budget: 400,
        imageUrl: "https://images.unsplash.com/photo-1598977123418-45f04b01d4ae?auto=format&fit=crop&w=600&q=80",
        detailedTips: "Visitez impérativement la grotte mystique de Phraya Nakhon vers 10h30 quand les rayons solaires illuminent le pavillon royal caché.",
        maxInfo: "Un sublime décor de montagnes de calcaire s'élevant verticalement au-dessus de marais côtiers sauvages."
      },
      {
        id: "p3-4",
        placeName: "Chiang Rai Immigration Office",
        day: 17,
        category: "Lodging",
        notes: "Camping sauvage de plage préservée à Ao Manao",
        lat: 11.7889,
        lng: 99.8167,
        duration: "6 nuits",
        budget: 1500,
        imageUrl: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=600&q=80",
        detailedTips: "Profitez d'une baignade paradisiaque. Les singes languis (singes à lunettes) y sont adorables, inoffensifs et très amicaux.",
        maxInfo: "Une plage militaire protégée en forme de croissant parfait, réputée pour ses eaux calmes et son sable fin."
      },
      {
        id: "p3-5",
        placeName: "Doi Phu Kha National Park",
        day: 23,
        category: "Camping",
        notes: "Camping forestier au Parc National de Khao Sok",
        lat: 8.9000,
        lng: 98.5333,
        duration: "5 nuits",
        budget: 2000,
        imageUrl: "https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?auto=format&fit=crop&w=600&q=80",
        detailedTips: "Louez un bateau traditionnel 'Longtail' pour explorer les pics karstiques géants émergeant du lac artificiel de Cheow Lan.",
        maxInfo: "Une des plus anciennes jungles tropicales humides de la Terre, abritant la fleur géante Rafflesia."
      },
      {
        id: "p3-6",
        placeName: "Bangkok",
        day: 28,
        category: "Lodging",
        notes: "Retour tranquille vers Bangkok, fin du voyage côtier",
        lat: 13.7563,
        lng: 100.5018,
        duration: "1 nuit",
        budget: 1100,
        imageUrl: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=600&q=80",
        detailedTips: "Faites halte pour déguster des poissons et fruits de mer frais le long de la côte de Samut Songkhram.",
        maxInfo: "Clôture d'une aventure paradisiaque de 4 semaines mêlant bivouac forestier et lagunes d'eau turquoise."
      }
    ]
  },
  {
    id: "preset-4",
    nameFr: "🛶 L'Ouest légendaire & Rivière Kwai (Jungles & Lacs)",
    nameTh: "🛶 เส้นทางผจญภัยแม่น้ำแควและปิล๊อกชายแดนพม่า",
    items: [
      {
        id: "p4-1",
        placeName: "123/99 Sarintara 1 Village, Samut Sakhon",
        day: 1,
        category: "Lodging",
        notes: "Point de départ - Logement gratuit chez l'habitant",
        lat: 13.5266,
        lng: 100.3161,
        duration: "1 nuit",
        budget: 0,
        imageUrl: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=600&q=80",
        detailedTips: "Vérifiez que votre voiture 4x4 ou SUV est prête à affronter les célèbres '399 virages' de la route vers Pilok.",
        maxInfo: "Départ immédiat vers l'Ouest sauvage, ses canyons, ses cascades et ses secrets d'histoire."
      },
      {
        id: "p4-2",
        placeName: "Wat Sangkat Rattanakhiri Uthai Thani",
        day: 5,
        category: "Attraction",
        notes: "Parc National d'Erawan - Baignades et cascades turquoise",
        lat: 14.3686,
        lng: 99.1436,
        duration: "6 nuits",
        budget: 600,
        imageUrl: "https://images.unsplash.com/photo-1598977123418-45f04b01d4ae?auto=format&fit=crop&w=600&q=80",
        detailedTips: "Randonnez de bonne heure jusqu'au 7ème niveau de la cascade. Portez des chaussures de marche pour éviter de glisser sur le calcaire humide.",
        maxInfo: "L'une des cascades les plus célèbres d'Asie du Sud-Est, sculptée dans des bassins rocheux d'un bleu émeraude cristallin."
      },
      {
        id: "p4-3",
        placeName: "Mae Wong National Park",
        day: 11,
        category: "Camping",
        notes: "Camping paisible au bord du grand lac de Srinakarin",
        lat: 14.5000,
        lng: 99.0000,
        duration: "6 nuits",
        budget: 350,
        imageUrl: "https://images.unsplash.com/photo-1546182990-dffeafbe841d?auto=format&fit=crop&w=600&q=80",
        detailedTips: "Installez votre bivouac directement sur la rive herbeuse. Le coucher de soleil sur le lac de barrage est un moment magique.",
        maxInfo: "Un havre de paix entouré de collines sauvages, idéal pour faire du kayak ou pêcher en toute tranquillité."
      },
      {
        id: "p4-4",
        placeName: "Doi Inthanon National Park",
        day: 17,
        category: "Camping",
        notes: "Bivouac culturel et visite du Pont Mon à Sangkhlaburi",
        lat: 15.1436,
        lng: 98.4519,
        duration: "6 nuits",
        budget: 1200,
        imageUrl: "https://images.unsplash.com/photo-1510070112810-d4e9a46d9e91?auto=format&fit=crop&w=600&q=80",
        detailedTips: "Levez-vous à 6h00 pour assister à l'aumône matinale des moines bouddhistes et traversez le pont historique en bois.",
        maxInfo: "Une cité frontalière magique habitée par des ethnies Mon et Karen, bordant un splendide lac de montagne."
      },
      {
        id: "p4-5",
        placeName: "Doi Pha Hom Pok National Park",
        day: 23,
        category: "Camping",
        notes: "Camping dans la brume à Pilok (Thong Pha Phum)",
        lat: 14.6722,
        lng: 98.3617,
        duration: "5 nuits",
        budget: 500,
        imageUrl: "https://images.unsplash.com/photo-1547036967-23d11aacaee0?auto=format&fit=crop&w=600&q=80",
        detailedTips: "Explorez la mine désaffectée de Somsak, dégustez des gâteaux locaux et profitez de l'incroyable ambiance brumeuse permanente.",
        maxInfo: "Un ancien village minier niché au sommet des montagnes frontalières du Myanmar, souvent enveloppé dans un brouillard épais féerique."
      },
      {
        id: "p4-6",
        placeName: "Bangkok",
        day: 28,
        category: "Lodging",
        notes: "Retour à Bangkok, restitution et bilan de l'itinéraire Ouest",
        lat: 13.7563,
        lng: 100.5018,
        duration: "1 nuit",
        budget: 1000,
        imageUrl: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=600&q=80",
        detailedTips: "Faites nettoyer votre voiture de location (souvent pleine de poussière des pistes de latérite) avant la restitution.",
        maxInfo: "Clôture de 4 semaines épiques passées au cœur de la jungle la plus reculée de l'Ouest thaïlandais."
      }
    ]
  },
  {
    id: "preset-5",
    nameFr: "🪵 Les Joyaux secrets du Mékong & Nan sauvage",
    nameTh: "🪵 เส้นทางเลียบริมแม่น้ำโขง ดอกชมพูภูคาและจังหวัดน่าน",
    items: [
      {
        id: "p5-1",
        placeName: "123/99 Sarintara 1 Village, Samut Sakhon",
        day: 1,
        category: "Lodging",
        notes: "Départ - Logement chez l'habitant gratuit",
        lat: 13.5266,
        lng: 100.3161,
        duration: "1 nuit",
        budget: 0,
        imageUrl: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=600&q=80",
        detailedTips: "Préparez vos cartes routières de l'Est lointain et du grand fleuve Mékong.",
        maxInfo: "Départ pour une expédition extraordinaire de 28 jours le long des frontières naturelles du Laos."
      },
      {
        id: "p5-2",
        placeName: "Phu Hin Rong Kla National Park",
        day: 5,
        category: "Camping",
        notes: "Bivouac d'altitude de Phu Hin Rong Kla et climat frais",
        lat: 16.9996,
        lng: 101.1278,
        duration: "6 nuits",
        budget: 300,
        imageUrl: "https://images.unsplash.com/photo-1501854140801-50d01698950b?auto=format&fit=crop&w=600&q=80",
        detailedTips: "Visitez le sentier historique des maquisards des années 70 et découvrez des canyons rocheux sculptés par l'érosion.",
        maxInfo: "Un parc unique situé à 1200m d'altitude, abritant d'immenses forêts de pins et d'incroyables chaos de roches plissées."
      },
      {
        id: "p5-3",
        placeName: "Si Satchanalai National Park",
        day: 11,
        category: "Camping",
        notes: "Halte pittoresque au village en bois de Chiang Khan",
        lat: 17.8942,
        lng: 101.6536,
        duration: "6 nuits",
        budget: 1500,
        imageUrl: "https://images.unsplash.com/photo-1590001155093-a3c66ab0c3ff?auto=format&fit=crop&w=600&q=80",
        detailedTips: "Louez un vélo pour arpenter la rue principale au coucher de soleil et observez le flot majestueux du Mékong.",
        maxInfo: "Une petite bourgade célèbre pour ses maisons en bois traditionnelles et ses rituels bouddhistes paisibles."
      },
      {
        id: "p5-4",
        placeName: "Doi Phu Kha National Park",
        day: 17,
        category: "Camping",
        notes: "Nan lointaine - Camping au-dessus de la brume",
        lat: 19.2014,
        lng: 101.0784,
        duration: "6 nuits",
        budget: 450,
        imageUrl: "https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?auto=format&fit=crop&w=600&q=80",
        detailedTips: "Conduisez prudemment sur la route 1081 (Route du Sel de Bo Kluea), réputée pour ses montées intenses et ses panoramas à 360°.",
        maxInfo: "Un joyau de nature reculé et sauvage abritant de sublimes mers de nuages d'altitude."
      },
      {
        id: "p5-5",
        placeName: "Khao Yai National Park",
        day: 23,
        category: "Camping",
        notes: "Visite du temple perché de Phu Thok (Bueng Kan)",
        lat: 18.1311,
        lng: 103.8814,
        duration: "5 nuits",
        budget: 1000,
        imageUrl: "https://images.unsplash.com/photo-1581888227599-779811939961?auto=format&fit=crop&w=600&q=80",
        detailedTips: "Ne souffrez pas de vertige ! L'ascension se fait par des passerelles en bois artisanales accrochées au flanc d'un monolithe rocheux titanesque.",
        maxInfo: "Un haut lieu spirituel bouddhiste représentant les sept niveaux de l'illumination dans la cosmologie bouddhiste."
      },
      {
        id: "p5-6",
        placeName: "Bangkok",
        day: 28,
        category: "Lodging",
        notes: "Retour à Bangkok, fin de l'expédition Mékong/Nan lointain",
        lat: 13.7563,
        lng: 100.5018,
        duration: "1 nuit",
        budget: 1000,
        imageUrl: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=600&q=80",
        detailedTips: "Dégustez un dernier dîner festif le long du fleuve Chao Phraya pour célébrer l'accomplissement de ces 4 semaines d'expédition.",
        maxInfo: "Retour triomphal à la capitale après avoir parcouru les confins sauvages de la frontière laotienne."
      }
    ]
  }
];

